# name: Redeploy Choreo

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: "* * * * *"

# jobs:
#   update-time:
#     runs-on: ubuntu-latest
#     steps:
#       - name: 'Checking'
#         uses: actions/checkout@v4

#       - name: 'Setting Python'
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.x'
      
#       - name: 'Get Current Time'   
#         run: python get_time.py

#       - name: Auto Commit
#         run: |
#           git config --global user.name 'francistrialman'
#           git config --global user.email 'francistrialman@gmail.com'
#           git add README.md
#           git commit -a -m "Update time"

#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
      
#       - name: Delete old workflow runs
#         uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
#         env:
#           GITHUB_TOKEN: ${{ github.token }}
#         with:
#           repository: ${{ github.repository }}
#           older-than-seconds: 3600

name: Redeploy Choreo

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  Redeploy:
    name: Redeploy Choreo

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 1

      - name: Renew README.md
        run: |
            DATE=$(date "+%Y/%m/%d %H:%M:%S")
            echo "${DATE}" > README.md
            git checkout --orphan tmp_work
            git branch -d main
            echo "DATE=${DATE}" >> $GITHUB_ENV

      - name: Upload to repository
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Auto deploy by Github Actions, ${{ env.DATE }}
          create_branch: true
          branch: main
          push_options: --force

      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository: ${{ github.repository }}
          older-than-seconds: 3600